import type { NextPage } from 'next'
import Head from 'next/head'
import WithAuth from '../lib/withAuth'

interface user {
  _id: string | "as";
  name: string;
  email: string;
  iat?: number;
}

const Home: NextPage<{ user?: user }> = ({ user }) => {

  return (
    <div className="min-h-screen w-screen flex justify-center items-center">

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>DASHBOARD</h1> <br />
      <h3>welcome {user?.name}</h3>

    </div>
  )
}

export default WithAuth(Home);