import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Login: NextPage = () => {
    return (
        <div className="h-screen w-screen flex justify-center items-center bg-teal-50">

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='h-full w-full bg-black'>
                <h1>a</h1>
            </main>

        </div>
    )
}

export default Login;